# Generated by Django 3.1.7 on 2021-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pcap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcap',
            name='data',
        ),
        migrations.AddField(
            model_name='pcap',
            name='direction',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='dst_addr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='dst_port',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='icmpv4',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='icmpv6',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='interface',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='ipv4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='ipv6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='is_inbound',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='is_loopback',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='is_outbound',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='payload',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='raw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='src_addr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='src_port',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='tcp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='udp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pcap',
            name='wd_addr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pcap',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
